config/routes.rb
Rails.application.routes.draw do
  resources :politicians
  resources :politicalparties
  resources :constituencies
  resources :states
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/politicalparty.rb
class Politicalparty
  include Mongoid::Document
end

app/controllers/politicalparties_controller.rb
class PoliticalpartiesController < ApplicationController
  before_action :set_politicalparty, only: [:show, :edit, :update, :destroy]

  # GET /politicalparties
  # GET /politicalparties.json
  def index
    @politicalparties = Politicalparty.all
  end

  # GET /politicalparties/1
  # GET /politicalparties/1.json
  def show
  end

  # GET /politicalparties/new
  def new
    @politicalparty = Politicalparty.new
  end

  # GET /politicalparties/1/edit
  def edit
  end

  # POST /politicalparties
  # POST /politicalparties.json
  def create
    @politicalparty = Politicalparty.new(politicalparty_params)

    respond_to do |format|
      if @politicalparty.save
        format.html { redirect_to @politicalparty, notice: 'Politicalparty was successfully created.' }
        format.json { render :show, status: :created, location: @politicalparty }
      else
        format.html { render :new }
        format.json { render json: @politicalparty.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /politicalparties/1
  # PATCH/PUT /politicalparties/1.json
  def update
    respond_to do |format|
      if @politicalparty.update(politicalparty_params)
        format.html { redirect_to @politicalparty, notice: 'Politicalparty was successfully updated.' }
        format.json { render :show, status: :ok, location: @politicalparty }
      else
        format.html { render :edit }
        format.json { render json: @politicalparty.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /politicalparties/1
  # DELETE /politicalparties/1.json
  def destroy
    @politicalparty.destroy
    respond_to do |format|
      format.html { redirect_to politicalparties_url, notice: 'Politicalparty was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_politicalparty
      @politicalparty = Politicalparty.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def politicalparty_params
      params.fetch(:politicalparty, {})
    end
end

app/helpers/politicalparties_helper.rb
module PoliticalpartiesHelper
end

app/views/politicalparties/_form.html.erb
<%= form_for(politicalparty) do |f| %>
  <% if politicalparty.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(politicalparty.errors.count, "error") %> prohibited this politicalparty from being saved:</h2>

      <ul>
      <% politicalparty.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/politicalparties/edit.html.erb
<h1>Editing Politicalparty</h1>

<%= render 'form', politicalparty: @politicalparty %>

<%= link_to 'Show', @politicalparty %> |
<%= link_to 'Back', politicalparties_path %>

app/views/politicalparties/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Politicalparties</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @politicalparties.each do |politicalparty| %>
      <tr>
        <td><%= link_to 'Show', politicalparty %></td>
        <td><%= link_to 'Edit', edit_politicalparty_path(politicalparty) %></td>
        <td><%= link_to 'Destroy', politicalparty, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Politicalparty', new_politicalparty_path %>

app/views/politicalparties/new.html.erb
<h1>New Politicalparty</h1>

<%= render 'form', politicalparty: @politicalparty %>

<%= link_to 'Back', politicalparties_path %>

app/views/politicalparties/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_politicalparty_path(@politicalparty) %> |
<%= link_to 'Back', politicalparties_path %>