config/routes.rb
Rails.application.routes.draw do
  resources :politicians
  resources :politicalparties
  resources :constituencies
  resources :states
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/constituency.rb
class Constituency
  include Mongoid::Document
end

app/controllers/constituencies_controller.rb
class ConstituenciesController < ApplicationController
  before_action :set_constituency, only: [:show, :edit, :update, :destroy]

  # GET /constituencies
  # GET /constituencies.json
  def index
    @constituencies = Constituency.all
  end

  # GET /constituencies/1
  # GET /constituencies/1.json
  def show
  end

  # GET /constituencies/new
  def new
    @constituency = Constituency.new
  end

  # GET /constituencies/1/edit
  def edit
  end

  # POST /constituencies
  # POST /constituencies.json
  def create
    @constituency = Constituency.new(constituency_params)

    respond_to do |format|
      if @constituency.save
        format.html { redirect_to @constituency, notice: 'Constituency was successfully created.' }
        format.json { render :show, status: :created, location: @constituency }
      else
        format.html { render :new }
        format.json { render json: @constituency.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /constituencies/1
  # PATCH/PUT /constituencies/1.json
  def update
    respond_to do |format|
      if @constituency.update(constituency_params)
        format.html { redirect_to @constituency, notice: 'Constituency was successfully updated.' }
        format.json { render :show, status: :ok, location: @constituency }
      else
        format.html { render :edit }
        format.json { render json: @constituency.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /constituencies/1
  # DELETE /constituencies/1.json
  def destroy
    @constituency.destroy
    respond_to do |format|
      format.html { redirect_to constituencies_url, notice: 'Constituency was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_constituency
      @constituency = Constituency.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def constituency_params
      params.fetch(:constituency, {})
    end
end

app/helpers/constituencies_helper.rb
module ConstituenciesHelper
end

app/views/constituencies/_form.html.erb
<%= form_for(constituency) do |f| %>
  <% if constituency.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(constituency.errors.count, "error") %> prohibited this constituency from being saved:</h2>

      <ul>
      <% constituency.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/constituencies/edit.html.erb
<h1>Editing Constituency</h1>

<%= render 'form', constituency: @constituency %>

<%= link_to 'Show', @constituency %> |
<%= link_to 'Back', constituencies_path %>

app/views/constituencies/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Constituencies</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @constituencies.each do |constituency| %>
      <tr>
        <td><%= link_to 'Show', constituency %></td>
        <td><%= link_to 'Edit', edit_constituency_path(constituency) %></td>
        <td><%= link_to 'Destroy', constituency, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Constituency', new_constituency_path %>

app/views/constituencies/new.html.erb
<h1>New Constituency</h1>

<%= render 'form', constituency: @constituency %>

<%= link_to 'Back', constituencies_path %>

app/views/constituencies/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_constituency_path(@constituency) %> |
<%= link_to 'Back', constituencies_path %>