config/routes.rb
Rails.application.routes.draw do
  resources :politicians
  resources :politicalparties
  resources :constituencies
  resources :states
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/politician.rb
class Politician
  include Mongoid::Document
end

app/controllers/politicians_controller.rb
class PoliticiansController < ApplicationController
  before_action :set_politician, only: [:show, :edit, :update, :destroy]

  # GET /politicians
  # GET /politicians.json
  def index
    @politicians = Politician.all
  end

  # GET /politicians/1
  # GET /politicians/1.json
  def show
  end

  # GET /politicians/new
  def new
    @politician = Politician.new
  end

  # GET /politicians/1/edit
  def edit
  end

  # POST /politicians
  # POST /politicians.json
  def create
    @politician = Politician.new(politician_params)

    respond_to do |format|
      if @politician.save
        format.html { redirect_to @politician, notice: 'Politician was successfully created.' }
        format.json { render :show, status: :created, location: @politician }
      else
        format.html { render :new }
        format.json { render json: @politician.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /politicians/1
  # PATCH/PUT /politicians/1.json
  def update
    respond_to do |format|
      if @politician.update(politician_params)
        format.html { redirect_to @politician, notice: 'Politician was successfully updated.' }
        format.json { render :show, status: :ok, location: @politician }
      else
        format.html { render :edit }
        format.json { render json: @politician.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /politicians/1
  # DELETE /politicians/1.json
  def destroy
    @politician.destroy
    respond_to do |format|
      format.html { redirect_to politicians_url, notice: 'Politician was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_politician
      @politician = Politician.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def politician_params
      params.fetch(:politician, {})
    end
end

app/helpers/politicians_helper.rb
module PoliticiansHelper
end

app/views/politicians/_form.html.erb
<%= form_for(politician) do |f| %>
  <% if politician.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(politician.errors.count, "error") %> prohibited this politician from being saved:</h2>

      <ul>
      <% politician.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/politicians/edit.html.erb
<h1>Editing Politician</h1>

<%= render 'form', politician: @politician %>

<%= link_to 'Show', @politician %> |
<%= link_to 'Back', politicians_path %>

app/views/politicians/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Politicians</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @politicians.each do |politician| %>
      <tr>
        <td><%= link_to 'Show', politician %></td>
        <td><%= link_to 'Edit', edit_politician_path(politician) %></td>
        <td><%= link_to 'Destroy', politician, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Politician', new_politician_path %>

app/views/politicians/new.html.erb
<h1>New Politician</h1>

<%= render 'form', politician: @politician %>

<%= link_to 'Back', politicians_path %>

app/views/politicians/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_politician_path(@politician) %> |
<%= link_to 'Back', politicians_path %>